function M=convert_transferorbit_struct2mat_perturbed(pert_transorbit)



M=[pert_transorbit.N,...
    pert_transorbit.delV,...
    pert_transorbit.delVD,...
    pert_transorbit.delVA,...
    pert_transorbit.r1(:)',pert_transorbit.r2(:)',pert_transorbit.v1(:)',pert_transorbit.v2(:)',...
    pert_transorbit.v0A(:)',pert_transorbit.v0B(:)'];
M=[M,pert_transorbit.timevec(:)',pert_transorbit.true_Altitude(:)',reshape(pert_transorbit.traj,1,size(pert_transorbit.traj,1)*6)];
    